# Generated by Django 5.2.16 on 2026-07-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('trigger_time', models.CharField(choices=[('manual', 'Manual'), ('after_correct', 'After Correct'), ('after_wrong', 'After Wrong'), ('challenge_end', 'Challenge End')], max_length=30)),
                ('effect_value', models.IntegerField()),
                ('resource_type', models.CharField(choices=[('none', 'None'), ('mana', 'Mana'), ('limited_use', 'Limited Use')], max_length=20)),
                ('max_uses_count', models.PositiveIntegerField()),
                ('resource_cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('character_class', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('max_hp', models.PositiveIntegerField()),
                ('max_mp', models.PositiveIntegerField()),
                ('attack_type', models.CharField(choices=[('melee', 'Melee'), ('ranged', 'Ranged')], max_length=10)),
                ('unlock_price', models.PositiveIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('asset_key', models.CharField(max_length=30)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='store.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_character')],
            },
        ),
    ]
