# Generated by Django 5.2.16 on 2026-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('warrior', 'Warrior'), ('archer', 'Archer'), ('rogue', 'Rogue'), ('mage', 'Mage'), ('alchemist', 'Alchemist')], max_length=30),
        ),
    ]
