# Generated by Django 5.2.16 on 2026-08-08 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_character_character_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='asset_key',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='skill',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='store.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='max_uses_count',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='resource_cost',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
