# Generated by Django 5.2.16 on 2026-08-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_character_asset_key_alter_character_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='max_uses_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='resource_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
