# Generated by Django 5.2.16 on 2026-08-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_skill_max_uses_count_alter_skill_resource_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='max_uses_count',
        ),
        migrations.AlterField(
            model_name='character',
            name='max_mp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
