# Generated by Django 5.2.16 on 2026-08-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_skill_max_uses_count_alter_character_max_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='trigger_time',
            field=models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], max_length=15),
        ),
    ]
