# Generated by Django 5.2.16 on 2026-08-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_skill_trigger_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='trigger_time',
            new_name='trigger_type',
        ),
    ]
