# Generated by Django 5.2.16 on 2026-07-16 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order_no', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit_type', models.CharField(blank=True, max_length=30)),
                ('order_no', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='mainquest.section')),
            ],
            options={
                'ordering': ['section', 'order_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('question_type', models.CharField(default='single_choice', max_length=30)),
                ('explanation', models.TextField(blank=True)),
                ('order_no', models.PositiveIntegerField(default=1)),
                ('available_for_daily', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mainquest.unit')),
            ],
            options={
                'ordering': ['unit', 'order_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order_no', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mainquest.question')),
            ],
            options={
                'ordering': ['question', 'order_no', 'id'],
                'constraints': [models.UniqueConstraint(fields=('question', 'order_no'), name='unique_option_order_in_question')],
            },
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('section', 'order_no'), name='unique_unit_order_in_section'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('unit', 'order_no'), name='unique_question_order_in_unit'),
        ),
    ]
