# Generated by Django 5.2.16 on 2026-07-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('asset_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order_no', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order_no', models.PositiveIntegerField()),
                ('unit_type', models.CharField(choices=[('common', 'Common'), ('boss', 'Boss')], default='common', max_length=10)),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='mainquest.boss')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='mainquest.section')),
            ],
            options={
                'ordering': ['section', 'order_no'],
                'constraints': [models.UniqueConstraint(fields=('section', 'order_no'), name='unique_unit_order_in_section')],
            },
        ),
    ]
