# Generated by Django 5.2.16 on 2026-08-13 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainquest', '0002_alter_unit_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='mainquest.section'),
        ),
    ]
