# Generated by Django 5.2.16 on 2026-08-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainquest', '0003_alter_unit_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='asset_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
