# Generated by Django 5.2.16 on 2026-07-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallengeRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('challenge_date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyChallengeQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_no', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.question')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_questions', to='dailyquest.dailychallengerecord')),
            ],
            options={
                'ordering': ['challenge', 'order_no'],
                'constraints': [models.UniqueConstraint(fields=('challenge', 'order_no'), name='unique_question_order_in_daily_challenge'), models.UniqueConstraint(fields=('challenge', 'question'), name='unique_question_in_daily_challenge')],
            },
        ),
    ]
