# Generated by Django 5.2.16 on 2026-08-08 09:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyquest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('daily_challenge_rewarded', models.BooleanField(default=False)),
                ('daily_quest1_rewarded', models.BooleanField(default=False)),
                ('daily_quest2_rewarded', models.BooleanField(default=False)),
                ('daily_quest3_rewarded', models.BooleanField(default=False)),
                ('progress_date', models.DateField(default=django.utils.timezone.localdate)),
                ('full_hp_units_passed_today', models.PositiveIntegerField(default=0)),
                ('questions_correct_today', models.PositiveIntegerField(default=0)),
                ('units_passed_today', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
