# Generated by Django 5.2.16 on 2026-08-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_usertaskdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskdata',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
