# Generated by Django 5.2.16 on 2026-08-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_usertaskdata_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertaskdata',
            name='alias',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
