# Generated by Django 5.2.16 on 2026-09-02 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainquest', '0004_alter_boss_asset_key'),
        ('userprofile', '0004_remove_usertaskdata_alias_userprofile_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unit_progress',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_users', to='mainquest.unit'),
        ),
    ]
