# Generated by Django 5.2.16 on 2026-09-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_userprofile_unit_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alias',
            field=models.CharField(blank=True, default='New User', max_length=10),
        ),
    ]
