# Generated by Django 5.2.16 on 2026-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_question_unique_question_order_in_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['order_no']},
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'order_no'), name='unique_option_order_in_question'),
        ),
    ]
